
/*This file is auto-generated by the Python script version.py. */


$(document).ready(function() {
  var link = '<a href="https://github.com/kgisl/FCC-Status/issues/new" target="_blank">';
  link += "v1.1-90-g0d126ff";
  link += '</a>';
  //console.log (link);
  $("#feedback").html(link);
});
