#!/usr/bin/env python

# Inspired by 
# https://gitfu.wordpress.com/2008/05/25/git-describe-great-another-way-to-refer-to-commits/
# http://gitready.com/beginner/2009/02/03/tagging.html


versionFile = "version.js"
defaultRepo = "http://github.com/kgisl/FCC-Status" 


#####################
## Get Version details
######################
import commands

status, repo = commands.getstatusoutput ("git ls-remote --get-url") 
if status: 
	repo = defaultRepo 
else:
	#repo = repo.split (".git")[0] 
	import re 
	repo = re.sub('\.git$', '', repo) 

status, version = commands.getstatusoutput ("git describe --tags --long")
if not status: 
	print ("Version: " + version)
else: 
	print "git describe return bad status!"
	version = "NA"

previous = None
try:
	fo = open (versionFile, "r")
	#print "Name of file opened ", fo.name 
	previous = fo.read()
	#print (previous)
	fo.close()
	
except:
	print ("Creating new version file...")


######
# Is it really necessary to update? 
######
if version == "NA": 
	pass 
elif previous and previous.find (version) != -1:
	print ("version.js already up-to-date!")
else: 
	####################
	## build JS code 
	####################
	fileContent = \
	'''\n\
/*This file is auto-generated by the Python script version.py. */
\n\
\n\
$(document).ready(function() {\n\
  var link = '<a href="https://github.com/kgisl/FCC-Status/issues/new" target="_blank">';\n\
'''
	fileContent = fileContent + '  link += "' + version + '";\n'
	#link += "Version 1.0";\n\
	fileContent2 = \
	'''  link += '</a>';\n\
  //console.log (link);\n\
  $("#feedback").html(link);\n\
});\n\
'''
	fileContent = fileContent + fileContent2
	##################
	## Just to be safe, we must backing up previous versionFile
	##################
	pass  # Not yet implemented 

	fo = open (versionFile, "w+")
	fo.write (fileContent)
	print (fileContent)
	print ("version.js updated with " + version)
	fo.close()

